[tool.poetry]
name = "litup-ide"
version = "0.1.0"
description = ""
authors = ["ist <ist@>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
textual = {extras = ["syntax"], version = "^0.76.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
